### PR TITLE
Use stream when option is string and ssl/tls defined

### PR DESCRIPTION
**Pull request by vovodroid**
Add transport class usage
Add try ... catch example

May be not optimal, but should work )))

### CODE REVIEW

**Comment by shen2** [comment]
Thanks a lot.
I've merged and optimized the code.

**Comment by vovodroid** [comment]
Great!
~~~
preg_match('/^(((tcp|udp|unix|ssl|tls):\/\/)?[\w\.\-]+)(\:(\d+))?/i', $options, $matches)
~~~
Does  **udp|unix** make sense ? Can C* listen on them?


By a way, if you use reg.exp. to parse string may be you can add user/password, like
~~~
ssl://user:password@host:port
~~~

**Comment by shen2** [comment]
```
ssl://user:password@host:port
```
It's a good idea.  but actually ssl protocol doesn't provide username and password argument.
Like mongodb or mysql, it should be
```
cassandra://user:password@host:port/keyspace
```

I hope $options argument should a valid fsockopen() argument.

**Comment by shen2** [comment]
udp|unix,
humm, maybe someday C* will provide unix socket way.  ^_^

**Comment by vovodroid** [comment]
~~~
 ssl protocol doesn't provide username and password argument.
~~~
Neither TCP does, those are not protocols but transports (from application layer POV), so I see no problem to add **user:password**
We are trying to do something useful  and usable, not http://en.wikipedia.org/wiki/Spherical_cow )))

Such solution will match both philosophy of user control and simplicity as well. I guess 99.(9)% of users will be happy just to use **ssl://user:password@host:port** without entering to philosophy at all )))

**Comment by shen2** [comment]
I hope it obey the standard, be clear and definite.
I don't think it's inconvenient to configure with array options. ^_^

**Comment by vovodroid** [comment]
For standard we should invent **cassandra**: and **cassandras:** )))

**Pull request merged**
