### PR TITLE
Add compatibility warning for time* types.

### PR DESCRIPTION
**Pull request by Divi**
See issue #45

### CODE REVIEW

**Comment by steambao** [comment]
Second that this is an issue

**Comment by shen2** [comment]
This is an issue.
I'd like to support it on 32-bit system, not only warn it.

**Comment by Divi** [comment]
Indeed, it will be great. But until the 32 bit fix is provided, it seems to be important to warn users, because I lost many hours finding why my timestamp was always set to `1970-...`.

This can avoid losing time.

**Comment by somanole** [comment]
Hi, I'm having the same issue on a 64-bit system. 

CentOS:
uname -a
Linux gait 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Java:
java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

It's driving me a bit nuts, any idea what's going on?

**Pull request closed without merging**
