### PR TITLE
Use stream to enable SSL

### PR DESCRIPTION
**Pull request by vovodroid**
I replaced socked with stream function to enable SSL/TLS usage. Configure nodes as following:
```
$nodes = [	
[
				'host'      => 'ssl://127.0.0.1',
				'username'  => 'cassandra',
				'password'  => 'cassandra',
				'timeout'    => 10 //seconds
		]
];
```
Socket options seems to be unavailable for PHP stream, so I replaced 'socket' option with a single option 'timeout' (for both read/write), default value is 30 seconds.

### CODE REVIEW

**Comment by shen2** [comment]
Sorry.  We need to find a better way lto support SSL.

If we use fwrite, fopen, fread,  it'll be synchronized and blocked when sending request.

stream_socket_write()  is asynchronized.

**Comment by shen2** [comment]
Maybe you can use the method stream_socket_enable_crypto() on the connected socket.

see this page:
http://stackoverflow.com/questions/14293404/how-to-use-low-level-socket-functions-socket-write-socket-read-to-handle-ssl-req?rq=1

Please rebase your code to the original, try this way.  I will merge it if it works.

Thanks.

**Comment by vovodroid** [comment]
-----------stream_socket_enable_crypto() 
No, it's not really socket method: 
http://php.net/manual/en/function.stream-socket-enable-crypto.php 
" stream: The stream resource."

I guess we can use http://php.net/manual/en/function.stream-set-blocking.php and http://php.net/manual/en/function.stream-select.php

I'm not great PHP developer ))), but I don't see any non-blocking settings in current code. queryAsync just send request with socket_write, , but getResponse waits for response with socket_read.  
So it's still blocking I/O, if I'm not wrong.

**Comment by shen2** [comment]
socket functions is non-blocking by default.

I'd like to use bottom level functions to ensure high performance.

fopen(), fread(), fwrite() is top level function.

If you really need to use SSL.  You can write another Cassandra\Connection, I'll make connection class switchable.

**Comment by shen2** [comment]
put these code in NodeSSL class, And I'll modify Connection.php line:73  like this:

$this->node = isset($this->options['ssl']) ? new Connection\Node($options) : new Connection\NodeSSL($options);

**Comment by shen2** [comment]
sorry, typo error:
```php
$this->node = isset($this->options['ssl']) ? new Connection\NodeSSL($options) : new Connection\Node($options);
```

**Comment by vovodroid** [comment]
We can use stream_set_blocking to switch stream to non-blocking mode.

---------put these code in NodeSSL 
It's not enough. Connection class also need to be replaced (it does read/write).

I don't think that overhead of stream functions really means something with comparison to overall performance - PHP, network, Cassandra itself. I would go to stream functions without hesitation.

**Comment by vovodroid** [comment]
By a way, I didn't really understand how asyncQuery works - getResponse() is blocking call, isn't it?
```
// Return a statement immediately
$statement = $connection->queryAsync($cql);

// Wait until received the response
$response = $statement->getResponse();

$rows = $response->fetchAll();
```
So how we benefit from async API?

**Comment by shen2** [comment]
```php
// Return a statement immediately
$statement = $connection->queryAsync($cql);  // wait 0ms

// you can do something else, or send more requests

// Wait until received the response
$response = $statement->getResponse();  // wait ~5ms

$rows = $response->fetchAll();
```

imagine you want to send 100 requests continuesly,
if use sync API, it will cost 200 network IO time,
if use async API, it will cost 2 network IO time.

**Comment by vovodroid** [comment]
So intention is to run batch of queryAsync() and then wait for result one-by-one getResponse() ?

In this case if socket_write is non-blocking and TCP buffer is full nothing will be sent and return value is not checked now.

http://php.net/manual/en/function.socket-write.php
```
It is perfectly valid for socket_write() to return zero which means no bytes have been written. Be sure to use the === operator to check for FALSE in case of an error. 
.........................
socket_write() does not necessarily write all bytes from the given buffer. It's valid that, depending on the network buffers etc., only a certain amount of data, even one byte, is written though your buffer is greater. You have to watch out so you don't unintentionally forget to transmit the rest of your data. 
```
Moreover, even if you check written bytes and discover, that not all or nothing was written what do you do? Currently it never be resent and to do this async I/O mechanism should be implemented. And partial (or zero) send can also happens in syncRequest, if socket is non-blocking by default.

**Comment by vovodroid** [comment]
------------socket functions is non-blocking by default.
Well, I write example:
```
<?php
echo "socket_create...\n";
$s = socket_create(AF_INET,SOCK_STREAM, SOL_TCP);

echo "socket_connect...\n";
socket_connect($s,"php.net",80);

//socket_set_nonblock($s);
echo "socket_read...\n";
$resp = socket_read($s,1000);

echo "read string ".$resp."\n";
?>
```
Try to run it, and then run with socket_set_nonblock uncommented. First run is blocked in socked_read.

**Comment by shen2** [comment]
when you use socket_read() to wait the response, of coz it should be blocked.

I mean use socket_write() to send request and do not use socket_read() to wait the response.

**Comment by vovodroid** [comment]
My points are:
1) Sockets are blocking by default, and I don't see any non-blocking settings in current code.
2) You can't just send data to non-blocking socket, data can be lost.

**Comment by shen2** [comment]
Hi, I update the code to support replaceable connection mode.
see: https://github.com/duoshuo/php-cassandra/commit/aff1ba6299e52ba776d2a76507e6f8526da15da4

Can you write a Connection class to support fopen/fsockopen way?

BTW, can you write a comment in php-cassandra.php to explain purpose of this file.
Thanks a lot.

**Comment by vovodroid** [comment]
-------- support replaceable connection mode.
Why can't we always use f..... methods and not complicate the code?

---------can you write a comment in php-cassandra.php to explain purpose of this file.
Sure )

**Comment by shen2** [comment]
socket functions are more basic and provide various error codes.
In some cloud enviornment,  fopen functions are not enabled.

**Comment by vovodroid** [comment]
Do you mean such case: http://stackoverflow.com/questions/9038694/fopen-is-not-working-on-my-server

Will such provider allow socket function?

**Comment by shen2** [comment]
Well, It's hard to say.  Who knows the service providers.

**Comment by vovodroid** [comment]
------------Can you write a Connection class to support fopen/fsockopen way?
OK, let me see latest changes.

**Pull request closed without merging**
